#!/bin/bash

set -e

SCRIPT_CMD_COMMAND_PREFIX="/c vcvarsall.bat"
SCRIPT_CMD_COMMAND_SUFFIX="&& call echo INCLUDE"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo %INCLUDE%"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo LIBPATH"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo %LIBPATH%"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo LIB"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo %LIB%"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo CLPATH"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call where cl"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo RCPATH"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call where rc"
SCRIPT_CMD_COMMAND_SUFFIX="${SCRIPT_CMD_COMMAND_SUFFIX} && call echo STOP"

SCRIPT_MSVC_INSTANCE_CMD_DIR_PATH=$('C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe' -latest -property installationPath)
SCRIPT_MSVC_INSTANCE_BASH_DIR_PATH=$(readlink -f "${SCRIPT_MSVC_INSTANCE_CMD_DIR_PATH}")
SCRIPT_MSVC_VCVARSALL_BASH_FILE_PATH=$(find "${SCRIPT_MSVC_INSTANCE_BASH_DIR_PATH}" -name 'vcvarsall.bat')
SCRIPT_MSVC_VCVARSALL_BASH_DIR_PATH=$(dirname "${SCRIPT_MSVC_VCVARSALL_BASH_FILE_PATH}")

pushd "${SCRIPT_MSVC_VCVARSALL_BASH_DIR_PATH}"

SCRIPT_MSVC_X86_CMD_ENV=$(cmd "${SCRIPT_CMD_COMMAND_PREFIX} x86 ${SCRIPT_CMD_COMMAND_SUFFIX}")

SCRIPT_MSVC_X64_X86_CMD_ENV=$(cmd "${SCRIPT_CMD_COMMAND_PREFIX} x64_x86 ${SCRIPT_CMD_COMMAND_SUFFIX}")

SCRIPT_MSVC_X64_CMD_ENV=$(cmd "${SCRIPT_CMD_COMMAND_PREFIX} x64 ${SCRIPT_CMD_COMMAND_SUFFIX}")

SCRIPT_MSVC_X86_X64_CMD_ENV=$(cmd "${SCRIPT_CMD_COMMAND_PREFIX} x86_x64 ${SCRIPT_CMD_COMMAND_SUFFIX}")

popd

echo '---'
echo "${SCRIPT_MSVC_X86_CMD_ENV}"
echo '---'
echo "${SCRIPT_MSVC_X64_X86_CMD_ENV}"
echo '---'
echo "${SCRIPT_MSVC_X64_CMD_ENV}"
echo '---'
echo "${SCRIPT_MSVC_X86_X64_CMD_ENV}"
echo '---'
echo ''

SCRIPT_MSVC_X86_CMD_INCLUDE=$(echo "${SCRIPT_MSVC_X86_CMD_ENV}" | awk '/INCLUDE/{flag=1;next}/LIBPATH/{flag=0}flag')

echo '==='
echo "${SCRIPT_MSVC_X86_CMD_INCLUDE}"
echo '==='
